import Navbar from "@/components/main/Navbar";
import connectMongo from "@/services/mongodb";
import { Inter } from "next/font/google";
import "./globals.css";
export const lnter = Inter({
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Eventry ",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connectMongo();
  return (
    <html lang="en">
      <body className={lnter.className}>
        <Navbar />
        <main className="py-8">{children}</main>
      </body>
    </html>
  );
}
