import Navbar from "@/components/main/Navbar";
import connectMongo from "@/services/mongodb";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./provider";
export const lnter = Inter({
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Eventry - Home ",
  description: "Generated by Eventry on the home page",
};

export default async function RootLayout({ children }) {
  await connectMongo();
  return (
    <html lang="en">
      <body className={lnter.className}>
        <AuthProvider>
          <Navbar />
          <main className="py-8">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
